import { api } from "./client.js";
import {
  createResourceTools,
  createCrudTools,
  createEnvTools,
  createStorageTools,
  createLifecycleTools,
} from "./factories.js";

export const applicationTools = [
  ...createResourceTools({
    resource: "applications",
    label: "Application",
    description: "applications in Coolify",
    api,
  }),
  ...createCrudTools({
    resource: "applications",
    label: "Application",
    createFields: {
      project_uuid: { type: "string", description: "Project UUID" },
      server_uuid: { type: "string", description: "Server UUID" },
      environment_name: { type: "string", description: "Environment name (default: production)" },
      name: { type: "string", description: "Application name" },
      description: { type: "string", description: "Optional description" },
      git_repository: { type: "string", description: "Git repository URL" },
      git_branch: { type: "string", description: "Git branch (default: main)" },
      build_pack: { type: "string", description: "Build pack: 'nixpacks', 'dockerfile', 'dockercompose', 'static'" },
      domains: { type: "string", description: "Comma-separated domains" },
      instant_deploy: { type: "string", description: "Optional — 'true' to deploy immediately" },
    },
    updateFields: {
      name: { type: "string", description: "New application name" },
      description: { type: "string", description: "New description" },
      git_repository: { type: "string", description: "New git repository URL" },
      git_branch: { type: "string", description: "New git branch" },
      domains: { type: "string", description: "New comma-separated domains" },
      build_pack: { type: "string", description: "New build pack" },
    },
    api,
  }),
  ...createEnvTools({ resource: "applications", api }),
  ...createStorageTools({ resource: "applications", api }),
  ...createLifecycleTools({ resource: "applications", api }),
  {
    name: "coolify_application_logs",
    description: "Get recent logs for an application container",
    schema: {
      uuid: { type: "string", description: "Application UUID" },
      lines: { type: "string", description: "Number of recent log lines (default 100)" },
    },
    handler: ({ uuid, lines }) => api(`/applications/${uuid}/logs?lines=${lines || 100}`),
  },
  {
    name: "coolify_application_deployments",
    description: "Get deployment history for an application",
    schema: { uuid: { type: "string", description: "Application UUID" } },
    handler: ({ uuid }) => api(`/applications/${uuid}/deployments`),
  },
  {
    name: "coolify_application_create_public",
    description: "Create an application from a public Git repository",
    schema: {
      project_uuid: { type: "string", description: "Project UUID" },
      server_uuid: { type: "string", description: "Server UUID" },
      environment_name: { type: "string", description: "Environment name" },
      name: { type: "string", description: "Application name" },
      git_repository: { type: "string", description: "Public Git repo URL" },
      git_branch: { type: "string", description: "Branch name" },
    },
    handler: (args) => api("/applications/public", "POST", args),
  },
  {
    name: "coolify_application_create_dockerfile",
    description: "Create an application from a Dockerfile",
    schema: {
      project_uuid: { type: "string", description: "Project UUID" },
      server_uuid: { type: "string", description: "Server UUID" },
      name: { type: "string", description: "Application name" },
      dockerfile: { type: "string", description: "Dockerfile content" },
      base_directory: { type: "string", description: "Base directory for the build" },
    },
    handler: (args) => api("/applications/dockerfile", "POST", args),
  },
  {
    name: "coolify_application_create_dockerimage",
    description: "Create an application from a prebuilt Docker image",
    schema: {
      project_uuid: { type: "string", description: "Project UUID" },
      server_uuid: { type: "string", description: "Server UUID" },
      name: { type: "string", description: "Application name" },
      docker_registry_image_name: { type: "string", description: "Docker image name" },
      docker_registry_image_tag: { type: "string", description: "Image tag (default: latest)" },
    },
    handler: (args) => api("/applications/dockerimage", "POST", args),
  },
  {
    name: "coolify_application_create_docker_compose",
    description: "Create an application from a Docker Compose file",
    schema: {
      project_uuid: { type: "string", description: "Project UUID" },
      server_uuid: { type: "string", description: "Server UUID" },
      name: { type: "string", description: "Application name" },
      docker_compose_raw: { type: "string", description: "Docker Compose file content" },
    },
    handler: (args) => api("/applications/dockercompose", "POST", args),
  },
  {
    name: "coolify_application_create_private_gh_app",
    description: "Create an application from a private repo via GitHub App integration",
    schema: {
      project_uuid: { type: "string", description: "Project UUID" },
      server_uuid: { type: "string", description: "Server UUID" },
      name: { type: "string", description: "Application name" },
      github_app_uuid: { type: "string", description: "GitHub App UUID" },
      git_repository: { type: "string", description: "Repository (owner/repo)" },
      git_branch: { type: "string", description: "Branch name" },
    },
    handler: (args) => api("/applications/private-github-app", "POST", args),
  },
  {
    name: "coolify_application_create_private_deploy_key",
    description: "Create an application from a private repo via deploy key",
    schema: {
      project_uuid: { type: "string", description: "Project UUID" },
      server_uuid: { type: "string", description: "Server UUID" },
      name: { type: "string", description: "Application name" },
      private_key_uuid: { type: "string", description: "SSH key UUID" },
      git_repository: { type: "string", description: "Git repo URL" },
      git_branch: { type: "string", description: "Branch name" },
    },
    handler: (args) => api("/applications/private-deploy-key", "POST", args),
  },
];
